#!/usr/bin/env bash

check_factor()
{
        factors=("$@")
        num=$(echo "${factors[0]}" | tr ':' '=')
        num1=1
        num2=1
        for i in "${factors[@]:1}"
        do
                if ((i > num1)); then
                        num2=$num1
                        num1=$i
                elif ((i > num2)); then
                        num2=$i
                fi
        done
        product=$(echo "$num1*$num2" | bc)
        for i in "${factors
